### ISSUE TITLE
What image formats are supported?

### ISSUE THREAD

**Issue by PontusTideman** [georapbox/meme-generator#30]
Hi!

What image formats are supported? Can´t see any information about it.

**Comment by georapbox** [comment]
Hi,

Supported image formats are jpg, jpeg, png, apng, gif, webp, avif.
With #31 they will be displayed inside the dropzone element.

**Comment by PontusTideman** [comment]
Oh, then I understand it. :) Still a freaking great meme maker mate.

**Comment by georapbox** [comment]
Thanks for the kind words! It's just a little project made mostly for fun to keep me busy when I have some free time.
