### ISSUE TITLE
how to give store image in database directly when page is lunch 

### ISSUE THREAD

**Issue by chAqibjaved** [georapbox/meme-generator#8]
Hi , in my case I have predefined image store in database , and user click on the image , I have the path of the image , how i load image in canvas . Thanks 

I make an new JavaScript function but how this work ?

function loadimagefrompath(image_path){
	
	  --- what code I right here to load the image from path 
	
}

**Comment by georapbox** [comment]
Hi @chAqibjaved ,

The value of input[type="file"] is read-only for security reasons, which means that you cannot programmatically load an image from path.

If what you want, though, is to just render the image in canvas here's a snippet that does that:
```js
const canvas = document.getElementById('canvas');
const ctx = canvas.getContext('2d');
const canvasPlaceholder = document.getElementById('canvasPlaceholder');
const img = new Image();

img.src = '<IMG_PATH>';

img.onload = (evt) => {
  canvas.width = evt.target.width;
  canvas.height = evt.target.height;
  canvas.classList.remove('d-none');
  canvasPlaceholder.classList.add('d-none');
  ctx.drawImage(img, 0, 0, canvas.width, canvas.height);  
}
```

Of course it's not enough to create the meme because you would need to also call the internal `draw` function that is responsible for drawing the canvas plus some other additional side effects. See [here](https://github.com/georapbox/meme-generator/blob/master/js/main.js#L119).

I guess the best way for now, would be to download the image so that it is available to your file system.

**Comment by chAqibjaved** [comment]
Thanks so much for your answers, the code you give me successfully load the images in the canvas but meme function not work .

Actually I want to make two option ,

First one user upload image from computer (working successfully already )
Second user select image from already provided imaged . (need solution for this)

I store the image path in database and image store on server , and user select one image and create the meme . the code successfully    load image but other function is not work .

how I call this function which value I passed 

function **handleFileSelect**(evt){

}

function **onImageLoaded**(evt) {
}

I like your hard work , I am very thankfull to you , if you provide me the solution . Thanks

**Comment by georapbox** [comment]
Sorry for late reply,

Actually to be honest, what you are trying to do is to replicate most of the functionality of the codebase. To properly address your issue would mean that I should support adding an image's path by using a text input. Of course that would also mean taking care of other arising issues, like handling potential errors while trying to fetch an image from the path, etc. I will try to create a prototype maybe when I find some time.

**Comment by chAqibjaved** [comment]
its great help for me , if you can make this prototype for me , I am actually stuck with this issues with 1 month . I want this to show prototype to college to get my degree .  and I have only 1 week remaining. I am very thankful to you if you give me this ,

**Comment by georapbox** [comment]
Hi,

Still kind of confused on what you really need. It would be helpful to know what you are working on. Are you developing a meme generator similar to this one for your college degree? If so, if I implemented this feature in this project would you be able to extract the pieces of code you need for your purpose?

**Comment by chAqibjaved** [comment]
Let I try to explain , yes I can create meme create . first user login in the app and its dashboard show to the user.
you can check the picture from following link [Dashboard](https://firebasestorage.googleapis.com/v0/b/smoke-inspection.appspot.com/o/memecreate%2FDashboard.PNG?alt=media&token=ec99836e-86c8-4d9e-b037-3683f635277a).
1) I have a requirements , if user not have image in his local computer we have provide sample image for edit purpose for this we have upload 10 images in server and show to the user available mems for edit . you can check here [available_mems_for_edit](https://firebasestorage.googleapis.com/v0/b/smoke-inspection.appspot.com/o/memecreate%2Favailablememes.PNG?alt=media&token=6986293f-83bb-417c-aecc-85662b908531)
please note this files actually on server and image path is store in database.
2) User clik any image , and image show in popup and also edit button to create the meme for this image .  [check here image](https://firebasestorage.googleapis.com/v0/b/smoke-inspection.appspot.com/o/memecreate%2Fedit_memes.PNG?alt=media&token=af1d8443-d3ea-435d-a3c2-9ac1ce1912b8) 
3) when edit image button is clicked i open the same page that you provide and image loaded in the canvas [see here ](https://firebasestorage.googleapis.com/v0/b/smoke-inspection.appspot.com/o/memecreate%2Fcrete_meme.PNG?alt=media&token=7325d2a6-006a-4eef-bf62-f72b95ccde76)
4) so main issues when i write in the text in input text text not write in the images. so currently your plugin give me two option first take picture from camera and its working fine and second take from local computer or drag from local computer its work fine . 
5) I am very thankful to you if you can make this to also work using url means load images from url also this solved my issues.
  how I call this function  function onImageLoaded(evt) {
}
when I successfully load image in canvas. hope you understand my issues . if you any question please inform me . thanks

**Comment by georapbox** [comment]
In the latest [commit](https://github.com/georapbox/meme-generator/commit/deeeceaf5631585cd4acf89912b76082f6755451) I have implemented selecting images from URL.

The only thing to have in mind is CORS requests. You need to make sure that the server that hosts your images sends the appropriate [Access-Allow-Control-Origin](https://developer.mozilla.org/docs/Web/HTTP/Headers/Access-Control-Allow-Origin) header so that you can fetch the files.

**Comment by chAqibjaved** [comment]
This is  exactly that I wanted and it works fine for me , thank you so much its great feature that you added . I really like your effort .
